querashop_queries/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('store.urls', namespace='')),
    # path('cart/', include('cart.urls', namespace=''))
]

store/urls.py
from django.urls import path
from .views import *

app_name = 'store'

urlpatterns = [
    path('', home),
    path('products_list/', products_list, name='products_list2'),
    path('product_detail/<int:pk>', product_detail, name='product_detail'),
    path('company_list/', company_list, name='company_list'),
    path('company_detail/<int:pk>', company_detail, name='company_detail'),
    path('products_list_category/<slug:category_slug>', products_list, name='product_list_by_category'),

]

cart/models.py
from django.db import models

# Create your models here.

store/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.urls import reverse


class Company(models.Model):
    name = models.CharField(max_length=50)
    phone = models.CharField(max_length=11)
    email = models.EmailField()


class Category(models.Model):
    name = models.CharField(max_length=30)
    slug = models.SlugField(max_length=100, unique=True)

    def get_absolute_url(self):
        return reverse('store:product_list_by_category', args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products', null=True)
    name = models.CharField(max_length=50)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    price = models.PositiveIntegerField()
    create = models.DateTimeField(auto_now_add=True, null=True)
    amount = models.PositiveSmallIntegerField(
        validators=[
            MaxValueValidator(1000)
        ])
    discount = models.PositiveSmallIntegerField(default=0,
                                                validators=[
                                                    MaxValueValidator(100)
                                                ])
    sold = models.PositiveSmallIntegerField(default=0)

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.pk])

    def __str__(self):
        return self.name


class Employee(models.Model):
    JOB_CHOICES = (
        ('Custodian', 'Custodian'),
        ('Cashier', 'Cashier'),
        ('Manager', 'Manager'),
        ('Stock clerk', 'Stock clerk')
    )

    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    age = models.PositiveSmallIntegerField(
        validators=[
            MaxValueValidator(100),
            MinValueValidator(18)
        ])
    job = models.CharField(choices=JOB_CHOICES, max_length=20)


class Customer(models.Model):
    LEVEL_CHOICES = (
        ('N', 'Normal'),
        ('G', 'Golden'),
    )

    name = models.CharField(max_length=40)
    phone = models.CharField(max_length=11)
    level = models.CharField(choices=LEVEL_CHOICES, max_length=1)


class Order(models.Model):
    product = models.ForeignKey(Product, on_delete=models.DO_NOTHING)
    customer = models.ForeignKey(Customer, on_delete=models.DO_NOTHING)
    time = models.DateTimeField()
    price = models.PositiveIntegerField()

cart/views.py
from django.shortcuts import render

# Create your views here.

store/views.py
from django.shortcuts import render, get_object_or_404
from .models import *
from django.http import JsonResponse


# Create your views here.

def products_list(request, category_slug=None):
    if category_slug:
        print(category_slug)
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category)
    else:
        products = Product.objects.all()
    return render(request, 'store/list.html', {'products': products})


def home(request):
    category = Category.objects.all()
    context = {
        'category': category
    }
    return render(request, 'store/home.html', context)


def product_detail(request, pk):
    product = get_object_or_404(Product, id=pk)
    context = {
        'product': product
    }
    return render(request, 'store/detail.html', context)


def company_list(request):
    companies = Company.objects.all()
    context = {
        'companies': companies
    }
    return render(request, 'store/company_lst.html', context)


def company_detail(request, pk):
    company = get_object_or_404(Company, id=pk)
    context = {
        'product': company
    }
    return render(request, 'store/company_detail.html', context)

store/templates/partials/best_selling_product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  {% for pdt in products %}
    <a href="{{ pdt.get_absolute_url }}">{{ pdt }}</a><br>
  {% endfor %}
</body>
</html>

store/templates/partials/discount_product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  {% for pdt in products %}
    <a href="{{ pdt.get_absolute_url }}">{{ pdt }}</a><br>
  {% endfor %}
</body>
</html>

store/templates/partials/new_product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% for pdt in products %}
        <a href="{{ pdt.get_absolute_url }}">{{ pdt }}</a><br>
    {% endfor %}
</body>
</html>

store/templates/store/company_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

store/templates/store/company_lst.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>cpm</title>
</head>
<body>
    {% for cpm in companies%}
    <a href="{% url 'store:company_detail' cpm.id%}">{{cpm.name}}</a><br>
    {% endfor %}
</body>
</html>

store/templates/store/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  {{product.name}}:{{product.price}}
</body>
</html>

store/templates/store/home.html
<!DOCTYPE html>
{% load store_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>home</title>
</head>
<body>
    <div dir="rtl">
        <a href="{% url 'store:company_list' %}">لیست کمپانی ها</a><br>
        <h4>دسته بندی:</h4>
        {% for cty in category %}
            <a href="{% url 'store:product_list_by_category' cty.slug %}">{{ cty }}</a><br>
        {% endfor %}
    </div>

    <h3>جدید ترین محصولات:</h3>
    {% new_products %}
    <hr>
    <h3>پرفروش ترین محصولات</h3>
    {% best_selling_product %}
    <hr>
    <h3>محصولات دارای تخفیف</h3>
    {% discount_product %}
</body>
</html>

store/templates/store/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% for product in products %}
    <a href="{{ product.get_absolute_url }}">{{product.name}}</a><br>
    {% endfor %}
</body>
</html>